config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resource :users, controller: 'registrations', only: [:create, :edit, :update] do
    get '/sign_up', action: 'new'
  end

  resource :users, controller: 'sessions', only: [] do
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create'
    delete '/sign_out', action: 'destroy'
  end

  resources :boards do
    member do
      patch :hide
      patch :open
      patch :lock
    end
    resources :posts, shallow: true
  end

  resources :posts, only:[] do
    resources :comments, shallow: true,  only: [:create , :destroy]
    member do
      post :favorite
    end
  end

  get 'pricing', to: 'pages#pricing'

  resource :cart, only: [:show, :destroy] do
    post 'add_item/:id', action: 'add_item' , as: 'add_item_path'
  end

  


end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true, length: { minimum: 4 }

  has_many :posts
  belongs_to :user, optional: true
  
  acts_as_paranoid
  include AASM

  aasm column: 'state', no_direct_assignment: true do
    state :open, initial: true
    state :hidden, :locked

    event :hide do
      transitions from: :open, to: :hidden
      after do
        "我是測試"
      end
    end

    event :lock do
      transitions from: :open, to: :locked
    end

    event :open do
      transitions from: [:hidden, :locked ], to: :open
    end
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board, only: [:show, :edit, :update, :destroy, :hide, :open, :lock]

  def index
    @boards = Board.all
  end

  def show
    @posts = @board.posts.order(id: :desc)
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.new(board_params)

    if @board.save
      redirect_to "/", notice: '成功新增看板'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to root_path, notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to root_path, notice: '看板已刪除'
  end

  def hide
    authorize  @board, :hide?
    @board.hide! if @board.may_hide?
    redirect_to boards_path, notice: '看板已隱藏'
  end

  def open
    @board.open! if @board.may_open?
    redirect_to boards_path, notice: '看板已開放'
  end

  def lock
    @board.lock! if @board.may_lock?
    redirect_to boards_path, notice: '看板已鎖定'
  end

  private
  def find_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def board_title_css(board)
    "board-title board-title-#{board.state}"
  end

  def check?(obj, type)
    obj.send("may#{type}?") && policy(obj).send("#{type}?")
  end

  # board.may_hide? && policy(board).hide?
end

app/views/boards/_form.html.erb
<% if board.errors.any? %>
  <ul>
    <% board.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(board) do |form| %>
  <%= form.label :title, '看板標題' %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

app/views/boards/edit.html.erb
<h1>編輯看板</h1>

<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<h1>看板列表</h1>

<%= link_to "新增看板", new_board_path %>

<ul>
<% @boards.each do |board| %>
  <li>
    <%= link_to "編輯", edit_board_path(board) %>
    <%= link_to "刪除", board,
                        method: 'delete',
                        data: { confirm: '是否確定刪除？' } %>
    <%= link_to "隱藏",  hide_board_path(board), method: 'PATCH' if board.may_hide? && policy(board).hide? %>
    <%= link_to "開放",  open_board_path(board), method: 'PATCH' if board.may_open? && policy(board).open? %>
    <%= link_to "鎖定",  lock_board_path(board), method: 'PATCH' if board.may_lock? && policy(board).lock? %>
    <%= link_to board.title, board, class: board_title_css(board) %>
  </li>
<% end %>
</ul>

app/views/boards/new.html.erb
<h1>新增看板</h1>

<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>
<%= link_to "新增文章", new_board_post_path(@board) %>





<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post %></li>
  <% end %>
</ul>